/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;


import java.awt.*;
import javax.swing.*;
import java.awt.event.*;


    

/**
 *
 * @author adi
 */
public class Latihan extends javax.swing.JFrame{
    
    
   private void tebalMiring(){
       int formathuruf=Font.PLAIN;
       formathuruf +=(tebal.isSelected())?Font.BOLD:Font.PLAIN;
       formathuruf +=(miring.isSelected())?Font.ITALIC:Font.PLAIN;
       Font font=tampil.getFont();
       tampil.setFont(new Font("",formathuruf,36));
       
   }
 
    
    /**
     * Creates new form Latihan
     */
    public Latihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tampil = new javax.swing.JLabel();
        merah = new javax.swing.JRadioButton();
        buttonGroup1.add(merah);
        biru = new javax.swing.JRadioButton();
        buttonGroup1.add(biru);
        kuning = new javax.swing.JRadioButton();
        buttonGroup1.add(kuning);
        hijau = new javax.swing.JRadioButton();
        buttonGroup1.add(hijau);
        tebal = new javax.swing.JCheckBox();
        miring = new javax.swing.JCheckBox();
        input = new javax.swing.JTextField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tampil.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        tampil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        merah.setText("Merah");
        merah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahActionPerformed(evt);
            }
        });

        biru.setText("Biru");
        biru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruActionPerformed(evt);
            }
        });

        kuning.setText("Kuning");
        kuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningActionPerformed(evt);
            }
        });

        hijau.setText("Hijau");
        hijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauActionPerformed(evt);
            }
        });

        tebal.setText("Bold");
        tebal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tebalItemStateChanged(evt);
            }
        });
        tebal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tebalActionPerformed(evt);
            }
        });

        miring.setText("Italic");
        miring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miringActionPerformed(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tebal)
                    .addComponent(miring))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(merah)
                                .addGap(52, 52, 52)
                                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(biru)
                                    .addComponent(kuning)
                                    .addComponent(hijau))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(merah)
                            .addComponent(tebal)
                            .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(miring)
                            .addComponent(biru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kuning))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ok)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hijau)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String tampilan=input.getText();
        tampil.setText(tampilan);
    }//GEN-LAST:event_okActionPerformed

    private void merahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahActionPerformed
        tampil.setForeground(Color.red);
    }//GEN-LAST:event_merahActionPerformed

    private void biruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruActionPerformed
        tampil.setForeground(Color.BLUE);
    }//GEN-LAST:event_biruActionPerformed

    private void kuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningActionPerformed
        tampil.setForeground(Color.YELLOW);
    }//GEN-LAST:event_kuningActionPerformed

    private void hijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauActionPerformed
     tampil.setForeground(Color.GREEN);
    }//GEN-LAST:event_hijauActionPerformed

    private void tebalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tebalActionPerformed
    tebalMiring();
        
    }//GEN-LAST:event_tebalActionPerformed

    private void miringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miringActionPerformed
     tebalMiring();
    }//GEN-LAST:event_miringActionPerformed

    private void tebalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tebalItemStateChanged
        
    }//GEN-LAST:event_tebalItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biru;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton hijau;
    private javax.swing.JTextField input;
    private javax.swing.JRadioButton kuning;
    private javax.swing.JRadioButton merah;
    private javax.swing.JCheckBox miring;
    private javax.swing.JButton ok;
    private javax.swing.JLabel tampil;
    private javax.swing.JCheckBox tebal;
    // End of variables declaration//GEN-END:variables
}
