/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author adi
 */
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
public class LatihanFormatHuruf extends javax.swing.JFrame {

    /**
     * Creates new form LatihanFormatHuruf
     */
    
    
    public void tebalmiring(){
        int formathuruf=Font.PLAIN;
        formathuruf+=(tebal.isSelected())?Font.BOLD:Font.PLAIN;
        formathuruf+=(miring.isSelected())?Font.ITALIC:Font.PLAIN;
        Font font=tampilan.getFont();
        tampilan.setFont(new Font(" ",formathuruf,36));
    }
    
    public LatihanFormatHuruf() {
        initComponents();
       
       
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tampilan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtinput = new javax.swing.JTextField();
        tebal = new javax.swing.JCheckBox();
        miring = new javax.swing.JCheckBox();
        merah = new javax.swing.JRadioButton();
        buttonGroup2.add(merah);
        biru = new javax.swing.JRadioButton();
        buttonGroup2.add(biru);
        kuning = new javax.swing.JRadioButton();
        buttonGroup2.add(kuning);
        hijau = new javax.swing.JRadioButton();
        buttonGroup2.add(hijau);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tampilan.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tampilan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampilan.setBorder(new javax.swing.border.MatteBorder(null));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinputActionPerformed(evt);
            }
        });

        tebal.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        tebal.setText("Bold");
        tebal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tebalActionPerformed(evt);
            }
        });

        miring.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        miring.setText("Italic");
        miring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miringActionPerformed(evt);
            }
        });

        merah.setText("Merah");
        merah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahActionPerformed(evt);
            }
        });

        biru.setText("Biru");
        biru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruActionPerformed(evt);
            }
        });

        kuning.setText("Kuning");
        kuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningActionPerformed(evt);
            }
        });

        hijau.setText("Hijau");
        hijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tebal)
                    .addComponent(miring))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(biru)
                                .addGap(17, 17, 17))
                            .addComponent(merah, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtinput)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuning)
                            .addComponent(hijau))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(tampilan, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tampilan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tebal)
                    .addComponent(merah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(miring)
                        .addComponent(biru)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kuning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hijau)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String display = txtinput.getText();
        tampilan.setText(display);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void merahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahActionPerformed
        
        tampilan.setForeground(Color.red);
    }//GEN-LAST:event_merahActionPerformed

    private void biruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruActionPerformed
       
        tampilan.setForeground(Color.BLUE);
    }//GEN-LAST:event_biruActionPerformed

    private void kuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningActionPerformed
        
        tampilan.setForeground(Color.YELLOW);
    }//GEN-LAST:event_kuningActionPerformed

    private void hijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauActionPerformed
        
        tampilan.setForeground(Color.GREEN);
    }//GEN-LAST:event_hijauActionPerformed

    private void txtinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinputActionPerformed

    private void tebalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tebalActionPerformed
    tebalmiring();
    }//GEN-LAST:event_tebalActionPerformed

    private void miringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miringActionPerformed
     tebalmiring();
        
    }//GEN-LAST:event_miringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
      
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LatihanFormatHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LatihanFormatHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LatihanFormatHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LatihanFormatHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LatihanFormatHuruf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biru;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton hijau;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton kuning;
    private javax.swing.JRadioButton merah;
    private javax.swing.JCheckBox miring;
    private javax.swing.JLabel tampilan;
    private javax.swing.JCheckBox tebal;
    private javax.swing.JTextField txtinput;
    // End of variables declaration//GEN-END:variables

    
}
